apiVersion: v1
kind: PersistentVolume
metadata:
  name: face-recognition-pv-unknown
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: local-storage
  local:
    path: /tmp/unknown_people
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: local-pvc
              operator: In
              values:
                - "true"