apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: face-recognition-pvc-unknown
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage