apiVersion: v1
kind: PersistentVolume
metadata:
  name: face-recognition-pvc-known
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: my-local-pvc
  local:
    path: /tmp/known_people
