apiVersion: v1
kind: Service
metadata:
  name: nsqlookup
spec:
  ports:
  - port: 4160
  selector:
    app: nsqlookup
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-nsqlookup
spec:
  selector:
    matchLabels:
      app: nsqlookup
  replicas: 1
  template:
    metadata:
      labels:
        app: nsqlookup
    spec:
      containers:
      - name: nsqlookup
        image: nsqio/nsq
        command: ["/nsqlookupd"]
        ports:
        - containerPort: 4160
          hostPort: 4160
        - containerPort: 4161
          hostPort: 4161
