apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-receiver
spec:
  selector:
    matchLabels:
      app: receiver
  replicas: 1
  template:
    metadata:
      labels:
        app: receiver
    spec:
      containers:
      - name: receiver
        image: skarlso/kube-receiver
        ports:
        - containerPort: 4150
          hostPort: 4150
        env:
        - name: MYSQL_CONNECTION
          value: mysql.default.svc.cluster.local
