apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-receiver
spec:
  selector:
    matchLabels:
      app: receiver
  replicas: 1
  template:
    metadata:
      labels:
        app: receiver
    spec:
      containers:
      - name: receiver
        image: skarlso/kube-receiver-alpine:latest
        ports:
        - containerPort: 4150
          hostPort: 4150
        env:
        - name: MYSQL_CONNECTION
          value: mysql.default.svc.cluster.local
        - name: MYSQL_USERPASSWORD
          valueFrom:
            secretKeyRef:
              name: kube-face-secret
              key: mysql_userpassword
        - name: MYSQL_PORT
          value: 3306
        - name: MYSQL_DBNAME
          value: kube
        - name: NSQ_ADDRESS
          value: 127.0.0.1
        - name: PRODUCER_ADDRESS
          value: 127.0.0.1:4150