apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-receiver
spec:
  selector:
    matchLabels:
      app: receiver
  replicas: 1
  template:
    metadata:
      labels:
        app: receiver
    spec:
      containers:
      - name: receiver
        image: skarlso/kube-receiver:latest
        ports:
        - containerPort: 4150
